added authRequired method
ChangePlusPlusVandy/MissionSAFE-backend pull request #14
Opened 2023-01-01 07:25 UTC by jiangerr

Unsure of a few thing, mainly whether naming/file hierarchy is correct (i.e. am I declaring this method in the right place?). Middleware still needs to be registered to proper endpoints

2023-01-01 16:19 UTC, alexbawa commented
> Unsure of a few thing, mainly whether naming/file hierarchy is correct (i.e. am I declaring this method in the right place?). Middleware still needs to be registered to proper endpoints

Great job!  I would change the folder name to middleware and the file name to auth.middleware.js

2023-01-01 16:20 UTC, alexbawa requested changes
I'll approve once Sam does

2023-01-10 19:24 UTC, samshefnie approved these changes
Looks good to me. Nice!

2023-01-10 19:43 UTC, alexbawa approved these changes

2023-01-10 20:43 UTC, merged